import React,{useEffect,useState} from "react";
import {enquiryApi,getLocalEnquiries,saveLocalEnquiry,removeLocalEnquiry} from "../services/api";
import {Panel,Badge,Pagination} from "../components/Ui";

const demo=[
{id:1,name:"Vignesh M",mobile:"9876543210",city:"Chennai",education:"B.E 2024",category:"Development",course:"Python Full Stack",admin:"Praveen",date:"18 Aug",status:"Pending"},
{id:2,name:"Anitha R",mobile:"9123456780",city:"Chrompet",education:"BCA 2025",category:"Data Analytics",course:"Data Analyst",admin:"Dhana",date:"19 Aug",status:"Positive"},
{id:3,name:"Karthik S",mobile:"9345678901",city:"Velachery",education:"B.Tech 2023",category:"Cloud",course:"AWS Cloud",admin:"Bhuvaneshwari",date:"20 Aug",status:"Hold"},
{id:4,name:"Monisha P",mobile:"9098765432",city:"Tambaram",education:"MBA 2024",category:"Fresher Placement",course:"Placement",admin:"Kokila",date:"21 Aug",status:"Positive"},
{id:5,name:"Arun Kumar",mobile:"9988776655",city:"Chennai",education:"B.E 2025",category:"Testing",course:"Software Testing",admin:"Swathy",date:"22 Aug",status:"Low"}];

const emptyForm={candidate_name:"",mobile:"",city:"",degree:"",passed_year:"",branch:"",category:"",course:"",admin:"",comments:"",next_followup_date:"",status:"Pending"};
const normalize=x=>({...x,name:x.name||x.candidate_name||"",education:x.education||x.degree||"",date:x.date||x.next_followup_date||"",status:x.status||x.final_status||x.finalStatus||"Pending"});
const mergeUnique=(preferredRows,otherRows)=>{const seen=new Set();return [...preferredRows,...otherRows].filter(row=>{const key=row.mobile||row.id||`${row.name}-${row.course}`;if(seen.has(key))return false;seen.add(key);return true;});};


export default function EnquiryList(){
	const [rows,setRows]=useState(demo),[q,setQ]=useState(""),[branch,setBranch]=useState(""),[category,setCategory]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1),[modal,setModal]=useState(null),[form,setForm]=useState(emptyForm),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
	useEffect(()=>{const local=getLocalEnquiries();enquiryApi.list().then(r=>setRows(mergeUnique((r.data.results||r.data).map(normalize),local.map(normalize)))).catch(()=>setRows(mergeUnique(local.map(normalize),demo)))},[]);
	const allFiltered=rows.filter(x=>(`${x.name} ${x.mobile}`.toLowerCase().includes(q.toLowerCase()))&&(!branch||x.branch===branch)&&(!category||x.category===category)&&(!status||x.status===status));
	const filtered=allFiltered.slice((page-1)*5,page*5);
	async function openView(row){try{const response=await enquiryApi.detail(row.id);setModal({type:"view",row:normalize({...row,...response.data})});}catch{setModal({type:"view",row});}}
	async function openEdit(row){setMessage("");try{const response=await enquiryApi.detail(row.id);setForm({...emptyForm,...response.data,candidate_name:response.data.candidate_name||row.name});}catch{setForm({...emptyForm,...row,candidate_name:row.name,degree:row.education});}setModal({type:"edit",row});}
	function change(event){setForm({...form,[event.target.name]:event.target.value});}
	async function remove(row){if(!window.confirm(`Delete the enquiry for ${row.name}?`))return;try{if(!String(row.id).startsWith("ST-")&&!String(row.id).startsWith("local-"))await enquiryApi.remove(row.id);}catch{}removeLocalEnquiry(row.id);setRows(rows.filter(item=>item.id!==row.id));}
	async function save(event){event.preventDefault();setSaving(true);setMessage("");try{await enquiryApi.update(modal.row.id,form);setMessage("Enquiry updated successfully.");}catch{saveLocalEnquiry({...form,id:modal.row.id,name:form.candidate_name});setMessage("Updated in demo mode. Connect Django API to persist it.");}setRows(rows.map(row=>row.id===modal.row.id?normalize({...row,...form,name:form.candidate_name,education:form.degree,date:form.next_followup_date}):row));setSaving(false);}
	return <Panel title="All Enquiries" subtitle="Manage and track all candidate enquiries" action={<a className="primary button-link" href="/add-enquiry">+ Add Enquiry</a>}>
		<div className="filters"><input placeholder="Search candidate / mobile..." value={q} onChange={e=>setQ(e.target.value)}/><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">All Branches</option><option>Keelkattalai</option><option>Velachery</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All Categories</option><option>Development</option><option>Data Analytics</option><option>Cloud</option><option>Testing</option><option>Fresher Placement</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option>{["Positive","Pending","Low","Hold","Negative","Joined"].map(x=><option key={x}>{x}</option>)}</select></div>
		<div className="table-scroll"><table><thead><tr>{["#","Candidate","Mobile","City","Education","Category","Course","Admin","Follow-up","Status","Action"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.id}</td><td><strong>{x.name}</strong></td><td>{x.mobile}</td><td>{x.city}</td><td>{x.education}</td><td>{x.category}</td><td>{x.course}</td><td>{x.admin}</td><td>{x.date}</td><td><Badge status={x.status}/></td><td><button className="icon-btn" aria-label={`View ${x.name}`} title="View" onClick={()=>openView(x)}>👁</button><button className="icon-btn" aria-label={`Edit ${x.name}`} title="Edit" onClick={()=>openEdit(x)}>✎</button><button className="icon-btn delete-btn" aria-label={`Delete ${x.name}`} title="Delete" onClick={()=>remove(x)}>🗑</button></td></tr>)}</tbody></table></div>
		{modal?.type==="view"&&<div className="modal-backdrop" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><div><h3>{modal.row.name}</h3><p>Previous follow-up details</p></div><button className="modal-close" onClick={()=>setModal(null)}>X</button></div><div className="detail-grid"><div><small>Mobile</small><strong>{modal.row.mobile}</strong></div><div><small>Status</small><Badge status={modal.row.status}/></div><div><small>Last follow-up</small><strong>{modal.row.date||"Not scheduled"}</strong></div><div><small>Course</small><strong>{modal.row.course}</strong></div></div><div className="followup-note">{modal.row.comments||"No previous follow-up discussion recorded."}</div></div></div>}
		{modal?.type==="edit"&&<div className="modal-backdrop" onClick={()=>setModal(null)}><form className="modal edit-modal" onSubmit={save} onClick={e=>e.stopPropagation()}><div className="modal-header"><div><h3>Edit Enquiry</h3><p>Update candidate and follow-up information</p></div><button type="button" className="modal-close" onClick={()=>setModal(null)}>X</button></div><div className="form-grid">{[["candidate_name","Candidate Name"],["mobile","Mobile Number"],["city","City / Place"],["degree","Degree"],["branch","Branch"],["category","Category"],["course","Course"],["admin","Admin"]].map(([name,label])=><div className="form-group" key={name}><label>{label}</label><input name={name} value={form[name]||""} onChange={change}/></div>)}<div className="form-group"><label>Next Follow-up Date</label><input type="date" name="next_followup_date" value={form.next_followup_date||""} onChange={change}/></div><div className="form-group"><label>Status</label><select name="status" value={form.status} onChange={change}>{["Positive","Pending","Low","Hold","Negative","Joined"].map(x=><option key={x}>{x}</option>)}</select></div><div className="form-group full"><label>Comments / Last Discussion</label><textarea name="comments" value={form.comments||""} onChange={change}/></div></div>{message&&<div className="success-message">{message}</div>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setModal(null)}>Close</button><button className="primary" disabled={saving}>{saving?"Updating...":"Update Enquiry"}</button></div></form></div>}
		<Pagination page={page} setPage={setPage} total={allFiltered.length}/>
	</Panel>;
}